### PR TITLE
add nvmrc

### PR DESCRIPTION
**Pull request by vikeen**
I had an issue installing modules because my default node was incompatible. Here I've added an `.nvmrc` to fix that, but not sure what version is actually getting used in production.

### CODE REVIEW

**Comment by gvan12** [comment]
We're actually using yarn, not sure if/how that honors nvmrc. That being said if it does, it's a welcome addition! Gonna read up a bit to make sure though.

**Comment by vikeen** [comment]
@gvan12, I use `yarn` as well. You still need the correct version of `node` though :)

**Comment by vikeen** [comment]
@gvan12, I'd also suggest removing the `npm` support from the docs. `yarn` and `npm` don't play well together and would likely be easier to give people only one option.

**Comment by gvan12** [comment]
Good call! And yeah, I think if it built fine we're good to go on node
version. Netlify honors nvmrc when set. I'll triple check when I'm at my
laptop and merge in. Thanks!

**Review by gvan12 — APPROVED** [review]
this looks good - Netlify is what we use to build so that would be our limiting factor. I googled a bit and saw that they added support for node v12 on their serverless functions so this is probably better than what I was using locally (v13.2). Thanks!

for reference.
https://www.netlify.com/blog/2019/12/04/node.js-12-now-available-for-netlify-functions/

**Pull request merged**
