### PR TITLE
Cleanup responsive layout & spacing

### PR DESCRIPTION
**Pull request by jamesonhill**
This resolves:
- https://github.com/RosieSews/masksnow/issues/93
- https://github.com/RosieSews/masksnow/issues/92
- https://github.com/RosieSews/masksnow/issues/94
- https://github.com/RosieSews/masksnow/issues/96

Issue 92 & 93:
Screen Shot 2020-04-13 at 8 53 20 PM

Issue 94:
Screen Shot 2020-04-13 at 8 53 43 PM

Issue 96:
Screen Shot 2020-04-13 at 8 54 07 PM

### CODE REVIEW

**Comment by gvan12** [comment]
Have you rebased this off of master by chance? There is a nasty layout bug
and I would loooove it if this also resolved that.

**Comment by jamesonhill** [comment]
I haven't, but I can do that now and check it out.

**Review by jcooter — APPROVED** [review]
LGTM

**Comment by jamesonhill** [comment]
Just added gatsby-plugin-styled-components to the gatsby-config. That fixes an issue where styles-component styles were not being applied on initial page load after a `gatsby build`

**Comment by gvan12** [comment]
ltgm. Thanks for fixing that bug too!

**Pull request merged**
